# Generated by Django 6.0.1 on 2026-03-05 05:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachSan',
            fields=[
                ('khach_san_id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_khach_san', models.CharField(blank=True, max_length=200, null=True)),
                ('dia_diem', models.CharField(blank=True, max_length=200, null=True)),
                ('gia_mot_dem', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('trang_thai', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'khach_san',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_tour', models.CharField(max_length=200)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('diem_khoi_hanh', models.CharField(blank=True, max_length=100, null=True)),
                ('diem_den', models.CharField(blank=True, max_length=100, null=True)),
                ('gia', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('so_ngay', models.IntegerField(blank=True, null=True)),
                ('so_cho', models.IntegerField(blank=True, null=True)),
                ('trang_thai', models.BooleanField(default=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tour',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=20, null=True)),
                ('dia_chi', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DatKhachSan',
            fields=[
                ('dat_khach_san_id', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_nhan', models.DateField(blank=True, null=True)),
                ('ngay_tra', models.DateField(blank=True, null=True)),
                ('tong_tien', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('trang_thai', models.CharField(blank=True, max_length=50, null=True)),
                ('nguoi_dung', models.ForeignKey(db_column='nguoi_dung_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('khach_san', models.ForeignKey(db_column='khach_san_id', on_delete=django.db.models.deletion.CASCADE, to='app.khachsan')),
            ],
            options={
                'db_table': 'dat_khach_san',
            },
        ),
        migrations.CreateModel(
            name='LienHe',
            fields=[
                ('lien_he_id', models.AutoField(primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('trang_thai', models.CharField(blank=True, max_length=50, null=True)),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.ForeignKey(db_column='nguoi_dung_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lien_he',
            },
        ),
        migrations.CreateModel(
            name='DatTour',
            fields=[
                ('dat_tour_id', models.AutoField(primary_key=True, serialize=False)),
                ('so_nguoi', models.IntegerField(blank=True, null=True)),
                ('tong_tien', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('trang_thai', models.CharField(blank=True, max_length=50, null=True)),
                ('ngay_dat', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.ForeignKey(db_column='nguoi_dung_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(db_column='tour_id', on_delete=django.db.models.deletion.CASCADE, to='app.tour')),
            ],
            options={
                'db_table': 'dat_tour',
            },
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('danh_gia_id', models.AutoField(primary_key=True, serialize=False)),
                ('so_sao', models.IntegerField(blank=True, null=True)),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('ngay_danh_gia', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.ForeignKey(db_column='nguoi_dung_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('khach_san', models.ForeignKey(blank=True, db_column='khach_san_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.khachsan')),
                ('tour', models.ForeignKey(blank=True, db_column='tour_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tour')),
            ],
            options={
                'db_table': 'danh_gia',
            },
        ),
    ]
